<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWt5w0bj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWt5w0bj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWt5w0bj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWt5w0bj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWt5w0bj\appDevDebugProjectContainer([
    'container.build_hash' => 'Wt5w0bj',
    'container.build_id' => 'ed719146',
    'container.build_time' => 1582070303,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWt5w0bj');
