<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMa2kefp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMa2kefp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMa2kefp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMa2kefp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMa2kefp\appDevDebugProjectContainer([
    'container.build_hash' => 'Ma2kefp',
    'container.build_id' => '51d1ee3d',
    'container.build_time' => 1581459778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMa2kefp');
