<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'anca_rebeca_full_calendar.service.calendar' shared service.

include_once $this->targetDirs[3].'\\vendor\\ancarebeca\\full-calendar-bundle\\Service\\Calendar.php';
include_once $this->targetDirs[3].'\\vendor\\ancarebeca\\full-calendar-bundle\\Service\\SerializerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\ancarebeca\\full-calendar-bundle\\Service\\Serializer.php';

return $this->services['anca_rebeca_full_calendar.service.calendar'] = new \AncaRebeca\FullCalendarBundle\Service\Calendar(new \AncaRebeca\FullCalendarBundle\Service\Serializer(), ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
