<?php

namespace Proxies\__CG__\BackBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \BackBundle\Entity\Commande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'id_u', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'id_bon', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'latlng', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'adresse', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'date', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'PrixT', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'qte', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'paiment', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'etatLivraion', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'livraison'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'id_u', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'id_bon', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'latlng', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'adresse', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'date', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'PrixT', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'qte', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'paiment', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'etatLivraion', '' . "\0" . 'BackBundle\\Entity\\Commande' . "\0" . 'livraison'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdBon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBon', []);

        return parent::getIdBon();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBon($id_bon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBon', [$id_bon]);

        return parent::setIdBon($id_bon);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixT(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixT', []);

        return parent::getPrixT();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixT(int $PrixT): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixT', [$PrixT]);

        parent::setPrixT($PrixT);
    }

    /**
     * {@inheritDoc}
     */
    public function getQte(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQte', []);

        return parent::getQte();
    }

    /**
     * {@inheritDoc}
     */
    public function setQte(int $qte): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQte', [$qte]);

        parent::setQte($qte);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiment(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiment', []);

        return parent::getPaiment();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiment(string $paiment): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiment', [$paiment]);

        parent::setPaiment($paiment);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatLivraion(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatLivraion', []);

        return parent::getEtatLivraion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatLivraion(string $etatLivraion): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatLivraion', [$etatLivraion]);

        parent::setEtatLivraion($etatLivraion);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivraison(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivraison', []);

        return parent::getLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivraison(string $livraison): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivraison', [$livraison]);

        parent::setLivraison($livraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTime $date): \BackBundle\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdU($id_u)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdU', [$id_u]);

        return parent::setIdU($id_u);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdU()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdU', []);

        return parent::getIdU();
    }

    /**
     * {@inheritDoc}
     */
    public function getLatlng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatlng', []);

        return parent::getLatlng();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatlng($latlng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatlng', [$latlng]);

        return parent::setLatlng($latlng);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

}
