<?php

namespace Proxies\__CG__\BackBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \BackBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'libelleP', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'prixAchat', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'prixVente', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'image', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'description', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'dateCreation', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'fournisseur', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'nbrVues', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'likeCount', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'dislikeCount', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'rating'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'libelleP', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'prixAchat', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'prixVente', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'image', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'description', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'dateCreation', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'fournisseur', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'nbrVues', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'likeCount', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'dislikeCount', '' . "\0" . 'BackBundle\\Entity\\Produit' . "\0" . 'rating'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getFournisseur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFournisseur', []);

        return parent::getFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setFournisseur($fournisseur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFournisseur', [$fournisseur]);

        return parent::setFournisseur($fournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrVues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrVues', []);

        return parent::getNbrVues();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrVues($nbrVues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrVues', [$nbrVues]);

        return parent::setNbrVues($nbrVues);
    }

    /**
     * {@inheritDoc}
     */
    public function getLikeCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLikeCount', []);

        return parent::getLikeCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setLikeCount($likeCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLikeCount', [$likeCount]);

        return parent::setLikeCount($likeCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDislikeCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDislikeCount', []);

        return parent::getDislikeCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDislikeCount($dislikeCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDislikeCount', [$dislikeCount]);

        return parent::setDislikeCount($dislikeCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleP($libelleP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleP', [$libelleP]);

        return parent::setLibelleP($libelleP);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleP', []);

        return parent::getLibelleP();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixAchat($prixAchat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixAchat', [$prixAchat]);

        return parent::setPrixAchat($prixAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixAchat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixAchat', []);

        return parent::getPrixAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixVente($prixVente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixVente', [$prixVente]);

        return parent::setPrixVente($prixVente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixVente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixVente', []);

        return parent::getPrixVente();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

}
