historique_index:
    path:     /index
    defaults: { _controller: "BackBundle:Historique:index" }
    methods:  GET


statrecherche:
    path:     /statrecherche
    defaults: { _controller: "BackBundle:Historique:statrecherche" }


historique_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Historique:show" }
    methods:  GET

historique_indexf:
    path:     /{id}/indexf
    defaults: { _controller: "BackBundle:Historique:indexf" }
    methods:  GET

historique_new:
    path:     /new
    defaults: { _controller: "BackBundle:Historique:new" }
    methods:  [GET, POST]

historique_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Historique:edit" }
    methods:  [GET, POST]

historique_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Historique:delete" }
    methods:  DELETE
