<?php

namespace BackBundle\Repository;

/**
 * BonReductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonReductionRepository extends \Doctrine\ORM\EntityRepository
{
}
