<?php

namespace BackBundle\Repository;

/**
 * CategoriefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriefRepository extends \Doctrine\ORM\EntityRepository
{
}
