<?php

namespace BackBundle\Repository;

/**
 * CommandefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandefRepository extends \Doctrine\ORM\EntityRepository
{
}
