<?php

namespace BackBundle\Repository;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends \Doctrine\ORM\EntityRepository
{
    function findByName(){
        $query=$this->getEntityManager()
            ->createQuery("select d from BackBundle:Depot d ORDER BY d.nom   ");
            //->setParameter('n',$val);
            //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }
    function findByCapacite(){
        $query=$this->getEntityManager()
            ->createQuery("select d from BackBundle:Depot d ORDER BY d.capacite   ");
        //->setParameter('n',$val);
        //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }
    function findAllDesc(){
        $query=$this->getEntityManager()
            ->createQuery("select d from BackBundle:Depot d ORDER BY d.id DESC  ");
        //->setParameter('n',$val);
        //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }
    function findAllDisponible(){
        $query=$this->getEntityManager()
            ->createQuery("select d from BackBundle:Depot d ORDER BY d.disponibilite DESC  ");
        //->setParameter('n',$val);
        //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }

}
