<?php

namespace BackBundle\Repository;

/**
 * LikeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findvote($user, $produit)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('DELETE FROM BackBundle:LikeProduit R WHERE R.produit = :id AND R.userId = :userid');
        $dql->setParameter(':id',$produit)
            ->setParameter(':userid', $user);
        return $dql->getResult();
    }
}
