<?php

namespace BackBundle\Repository;

/**
 * reponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reponseRepository extends \Doctrine\ORM\EntityRepository
{
    function robot($fa){


        $query=$this->getEntityManager()->createQuery("select e from BackBundle:reponse e where e.question = '$fa'");
        return $query->getResult();

    }
}
