<?php

namespace BackBundle\Repository;

/**
 * RepresentantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentantRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllDesc(){
        $query=$this->getEntityManager()
            ->createQuery("select d from BackBundle:Representant d ORDER BY d.id DESC  ");
        //->setParameter('n',$val);
        //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }
    function findName($nom){
        $query=$this->getEntityManager()
            ->createQuery("select c from BackBundle:Representant c where c.nom LIKE '%".$nom."%' or c.prenom like'%".$nom."%'  or c.email like'%".$nom."%' 
                       or  c.addresse like'%".$nom."%'");
        //->setParameter('n',$val);
        //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }
}
