<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDuh6hcz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDuh6hcz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDuh6hcz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDuh6hcz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDuh6hcz\appProdProjectContainer([
    'container.build_hash' => 'Duh6hcz',
    'container.build_id' => 'f10478e7',
    'container.build_time' => 1580639990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDuh6hcz');
