<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'discutea.forum.pagin' shared service.

include_once $this->targetDirs[3].'\\vendor\\discutea\\forum-bundle\\Discutea\\DForumBundle\\Component\\Pagin.php';

return $this->services['discutea.forum.pagin'] = new \Discutea\DForumBundle\Component\Pagin(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'}, ${($_ = isset($this->services['knp_paginator']) ? $this->services['knp_paginator'] : $this->load('getKnpPaginatorService.php')) && false ?: '_'}, $this->parameters['discutea_forum.pagination'], 'p');
