<?php

namespace BackBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommandeNonLivre(){
        $qb=$this->createQuery("SELECT u FROM COMMANDE u");

          //  ->where('c.etatLivraion = :nonAffecte' )
            //->orWhere( 'c.etatLivraion = :Affecte')
           /// ->setParameter('nonAffecte', "non affecté")
          //  ->setParameter('Affecte', "affecté")

        return $qb->getResult();

    }
}
