<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGzvcwni\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGzvcwni/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGzvcwni.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGzvcwni\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGzvcwni\appDevDebugProjectContainer([
    'container.build_hash' => 'Gzvcwni',
    'container.build_id' => '69293162',
    'container.build_time' => 1581487976,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGzvcwni');
