<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO5m1nwg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO5m1nwg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO5m1nwg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO5m1nwg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerO5m1nwg\appDevDebugProjectContainer([
    'container.build_hash' => 'O5m1nwg',
    'container.build_id' => 'c1332483',
    'container.build_time' => 1581201398,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO5m1nwg');
