<?php

namespace BackBundle\Repository;

use Doctrine\ORM\EntityRepository;
use BackBundle\Entity\Commande;
/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c
                FROM BackBundle:Commande c
                WHERE c.id LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
