<?php

namespace BackBundle\Repository;

/**
 * Livraison_PlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Livraison_PlanningRepository extends \Doctrine\ORM\EntityRepository
{
}
