<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2ieavo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2ieavo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE2ieavo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE2ieavo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerE2ieavo\appDevDebugProjectContainer([
    'container.build_hash' => 'E2ieavo',
    'container.build_id' => 'e4457ffa',
    'container.build_time' => 1580999259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2ieavo');
