back_homepage:
    path:     /aa
    defaults: { _controller: BackBundle:Default:index }

ajoutTypeVehicule:
    path:     /ajoutType
    defaults: { _controller: BackBundle:Livraison:AjouterTypeVehicule }

afficherTypeVehicules:
    path:     /afficherTypes
    defaults: { _controller: BackBundle:Livraison:AfficherTypeVehicule }

supprimerTypeVehicule:
    path:     /supprimerType
    defaults: { _controller: BackBundle:Livraison:SupprimerTypeVehicule }

modifierTypeVehicule:
    path:     /modifierType
    defaults: { _controller: BackBundle:Livraison:ModifierTypeVehicule }

ajoutVehicule:
    path:     /ajoutVehicule
    defaults: { _controller: BackBundle:Livraison:AjouterVehicule }


afficheVehicule:
    path:     /afficheVehicule
    defaults: { _controller: BackBundle:Livraison:AfficherVehicule }

supprimerVehicule:
    path:     /supprimerVehicule
    defaults: { _controller: BackBundle:Livraison:SupprimerVehicule }

modifierVehicule:
    path:     /modifierVehicule
    defaults: { _controller: BackBundle:Livraison:ModifierVehicule }

affichePlannigDay:
    path:     /affichePlanningDay
    defaults: { _controller: BackBundle:Livraison:AfficherVPlanningDay }

afficherCommandeNonLivre:
    path:     /AfficherCommandeNonLivre
    defaults: { _controller: BackBundle:Livraison:AfficherCommandeNonLivre }

affecterLivraison:
    path:     /affecterLivraison
    defaults: { _controller: BackBundle:Livraison:AffecterLivraison }

afficherLivreurDispo:
    path:     /afficherLivreurDispo
    defaults: { _controller: BackBundle:Livraison:AfficherLivreurDispo }

afficherVehiculeDispo:
    path:     /afficherVehiculeDispo
    defaults: { _controller: BackBundle:Livraison:AfficherVehiculeDispo }

AffecterCommande:
    path:     /AffecterCommande
    defaults: { _controller: BackBundle:Livraison:AffecterCommande }

LivrerCommande:
    path:     /LivrerCommande
    defaults: { _controller: BackBundle:Livraison:LivrerCommande }


ModifierVehicule2:
    path:     /ModifierVehicule2
    defaults: { _controller: BackBundle:Livraison:ModifierVehicule2 }

ModifierVehicule22:
    path:     /ModifierVehicule22
    defaults: { _controller: BackBundle:Livraison:ModifierVehicule22 }

ModifierVehiculePop:
  path:     /ModifierVehiculePop
  defaults: { _controller: BackBundle:Livraison:ModifierVehiculePop }