<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRvsqdeg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRvsqdeg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRvsqdeg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRvsqdeg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRvsqdeg\appDevDebugProjectContainer([
    'container.build_hash' => 'Rvsqdeg',
    'container.build_id' => '00c0fce7',
    'container.build_time' => 1582699065,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRvsqdeg');
